import { useEffect, useMemo, useState } from 'react'
import { NavLink, Navigate, Route, Routes, useNavigate } from 'react-router-dom'
import { AlertTriangle, BookOpenCheck, BriefcaseMedical, CheckCircle2, ClipboardCheck, FileSearch, Files, Gauge, History, LogOut, Menu, Search, Settings, ShieldCheck, TriangleAlert, Users, X } from 'lucide-react'
import { api, getToken } from './api'

type User = {id:number; username:string; full_name:string; email:string; role:string; department?:string; job_role?:string; active:boolean}
const rank:Record<string,number>={user:1,manager:2,qa:3,admin:4}

function Login({onLogin}:{onLogin:(u:User)=>void}){
  const [username,setUsername]=useState('admin'), [password,setPassword]=useState('ChangeMeNow!2026'), [error,setError]=useState('')
  const nav=useNavigate()
  async function submit(e:any){e.preventDefault();setError('');try{const r=await api.login(username,password);onLogin(r.user);nav('/')}catch(e:any){setError(e.message)}}
  return <div className="loginPage"><div className="loginCard"><Brand/><div className="eyebrow">Secure quality portal</div><h1>Welcome back</h1><p>Electronic Quality Management System</p>{error&&<div className="error">{error}</div>}<form onSubmit={submit}><label>Username<input value={username} onChange={e=>setUsername(e.target.value)}/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary">Sign in</button></form></div></div>
}

function Brand(){return <div className="brand"><div className="brandMark">E</div><div><strong>Eaststone</strong><span>ELECTRONIC QUALITY MANAGEMENT SYSTEM</span></div></div>}

function Shell({user,setUser,children}:{user:User;setUser:(u:any)=>void;children:any}){
  const [open,setOpen]=useState(false);const nav=useNavigate();const can=(r:string)=>(rank[user.role]||0)>=rank[r]
  const links=[['/',Gauge,'Overview',true],['/training',BookOpenCheck,'My training',true],['/documents',Files,'Controlled documents',true],['/complaints',BriefcaseMedical,'Complaints',true],['/deviations',TriangleAlert,'Deviations',true],['/capa',ClipboardCheck,'CAPA',true],['/oos',AlertTriangle,'OOS',true],['/risk',ShieldCheck,'Risk assessments',true],['/team',Users,'People & training',can('manager')],['/audit',History,'Audit trail',can('qa')],['/system',Settings,'System & permissions',can('qa')]] as const
  function logout(){api.logout();setUser(null);nav('/login')}
  return <div className="shell"><header><button className="icon" onClick={()=>setOpen(true)}><Menu/></button><div className="wordmark">EASTSTONE</div><div className="headerLine"/><div className="subtitle">Quality & Training</div><div className="account"><strong>{user.full_name}</strong><span>{user.role.toUpperCase()}</span></div></header>{open&&<div className="scrim" onClick={()=>setOpen(false)}/>}<aside className={open?'open':''}><div className="drawerHead"><Brand/><button className="close" onClick={()=>setOpen(false)}><X/></button></div><div className="drawerLabel">WORKSPACE</div><nav>{links.filter(x=>x[3]).map(([to,Icon,label])=><NavLink key={to} to={to as string} end={to==='/'} onClick={()=>setOpen(false)}><Icon size={21}/><span>{label}</span><b>›</b></NavLink>)}</nav><div className="drawerAccount"><div className="avatar">{user.full_name[0]}</div><div><strong>{user.full_name}</strong><span>{user.role.toUpperCase()}</span></div><button onClick={logout}><LogOut size={18}/></button></div></aside><main>{children}</main></div>
}

function Hero({eyebrow,title,text}:{eyebrow:string;title:string;text:string}){return <section className="hero"><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{text}</p></section>}
function Metric({label,value,note,tone}:{label:string;value:any;note:string;tone:string}){return <div className="metric"><div className={`dot ${tone}`}/><div><span>{label}</span><strong>{value}</strong><small>{note}</small></div></div>}
function Loading(){return <div className="loading">Loading…</div>}

function Dashboard(){const[d,setD]=useState<any>(null);useEffect(()=>{api.dashboard().then(setD)},[]);if(!d)return <Loading/>;const t=d.training;return <><Hero eyebrow="Quality overview" title="Compliance at a glance" text="Training position and open quality-system activity."/><div className="metrics"><Metric label="Training compliance" value={`${t.percentage}%`} note="Minimum target 80%" tone="green"/><Metric label="Read & understood" value={t.completed} note="Current completed training" tone="blue"/><Metric label="Outstanding" value={t.outstanding} note="Requires completion" tone="yellow"/><Metric label="Overdue" value={t.overdue} note="Requires attention" tone="red"/></div><div className="grid"><section className="card"><h2>My training position</h2><div className="donut" style={{background:`conic-gradient(#2e8b6d 0 ${t.percentage}%, #e8b84f ${t.percentage}% 100%)`}}><div><strong>{t.percentage}%</strong><span>compliant</span></div></div></section><section className="card"><h2>Open QMS activity</h2>{Object.entries(d.qms).map(([k,v]:any)=><div className="row" key={k}><span>{k.toUpperCase()}</span><b>{v}</b></div>)}</section></div></>}

const labels:any={complaint:['Customer & product quality','Complaints'],deviation:['Quality events','Deviations'],capa:['Corrective action','CAPA'],oos:['Laboratory quality','Out of Specification'],risk:['Quality risk management','Risk assessments']}
function QmsList({kind}:{kind:string}){const[rows,setRows]=useState<any[]>([]);const[show,setShow]=useState(false);const[form,setForm]=useState({title:'',description:'',severity:'Medium',department:''});async function load(){setRows(await api.records(kind))}useEffect(()=>{load()},[kind]);async function create(e:any){e.preventDefault();await api.createRecord(kind,form);setShow(false);setForm({title:'',description:'',severity:'Medium',department:''});load()}const l=labels[kind];return <><Hero eyebrow={l[0]} title={l[1]} text={`Create, investigate, assign and close ${l[1].toLowerCase()} with a traceable audit history.`}/><div className="toolbar"><button className="primary" onClick={()=>setShow(!show)}>+ New {kind}</button></div>{show&&<form className="card formGrid" onSubmit={create}><label>Title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/></label><label>Severity<select value={form.severity} onChange={e=>setForm({...form,severity:e.target.value})}><option>Low</option><option>Medium</option><option>High</option><option>Critical</option></select></label><label>Department<input value={form.department} onChange={e=>setForm({...form,department:e.target.value})}/></label><label className="wide">Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} required/></label><button className="primary">Create record</button></form>}<section className="card tableCard"><table><thead><tr><th>Reference</th><th>Title</th><th>Status</th><th>Severity</th><th>Department</th><th>Due</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{r.reference}</b></td><td>{r.title}</td><td><span className="pill">{r.status}</span></td><td>{r.severity||'—'}</td><td>{r.department||'—'}</td><td>{r.due_date||'—'}</td></tr>)}</tbody></table></section></>}

function Documents({user}:{user:User}){const[q,setQ]=useState('');const[rows,setRows]=useState<any[]>([]);const[result,setResult]=useState<any>(null);useEffect(()=>{const t=setTimeout(()=>api.documents(q).then(setRows),150);return()=>clearTimeout(t)},[q]);async function sync(){setResult(await api.syncDocuments());setRows(await api.documents(q))}return <><Hero eyebrow="Controlled documents" title="Approved document library" text="Search the current controlled SOPs, forms and approved procedures available from the Eaststone document source."/><div className="toolbar">{['qa','admin'].includes(user.role)&&<button className="primary" onClick={sync}>Synchronise approved folder</button>}</div>{result&&<div className="notice">Sync: {JSON.stringify(result)}</div>}<div className="search"><Search size={20}/><input placeholder="Search reference or title" value={q} onChange={e=>setQ(e.target.value)}/></div><div className="docList">{rows.map(d=><div className="docCard" key={d.id}><div className="docIcon"><FileSearch/></div><div><b>{d.reference}</b><h3>{d.title}</h3><p>Revision {d.revision||'—'} · {d.type}</p></div><a className="secondary" href={`/api/documents/${d.id}/open`} target="_blank">Open</a></div>)}</div></>}

function Training(){const[rows,setRows]=useState<any[]>([]);const[signing,setSigning]=useState<number|null>(null);const[name,setName]=useState('');const[password,setPassword]=useState('');async function load(){setRows(await api.training())}useEffect(()=>{load()},[]);async function sign(id:number){await api.acknowledge(id,{signed_name:name,password});setSigning(null);setName('');setPassword('');load()}return <><Hero eyebrow="Training" title="My training" text="Open the current approved procedure, read it, then electronically confirm Read & Understood."/><div className="docList">{rows.map(r=><div className="docCard" key={r.id}><div><b>{r.reference}</b><h3>{r.title}</h3><p>Revision {r.revision} · Due {r.due_date||'not set'}</p></div><span className={`pill ${r.status==='COMPLETED'?'ok':''}`}>{r.status}</span>{r.status!=='COMPLETED'&&<button className="secondary" onClick={()=>setSigning(r.id)}>Read & Understood</button>}{signing===r.id&&<div className="signBox"><label>Full name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary" onClick={()=>sign(r.id)}>Electronically sign</button></div>}</div>)}</div></>}

function People(){const[rows,setRows]=useState<any[]>([]);useEffect(()=>{api.users().then(setRows)},[]);return <><Hero eyebrow="People & access" title="People, roles & permissions" text="Monitor accounts, departments, job roles and access levels."/><section className="card tableCard"><table><thead><tr><th>Name</th><th>Username</th><th>Department</th><th>Job role</th><th>Permission</th></tr></thead><tbody>{rows.map(u=><tr key={u.id}><td><b>{u.full_name}</b></td><td>{u.username}</td><td>{u.department||'—'}</td><td>{u.job_role||'—'}</td><td><span className="pill">{u.role}</span></td></tr>)}</tbody></table></section></>}
function Audit(){const[rows,setRows]=useState<any[]>([]);useEffect(()=>{api.audit().then(setRows)},[]);return <><Hero eyebrow="Data integrity" title="Audit trail" text="Traceable system and user activity."/><section className="card tableCard"><table><thead><tr><th>Date/time</th><th>Action</th><th>Entity</th><th>Details</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{String(r.created_at)}</td><td><b>{r.action}</b></td><td>{r.entity_type} {r.entity_id||''}</td><td>{r.details||'—'}</td></tr>)}</tbody></table></section></>}
function System(){return <><Hero eyebrow="System administration" title="Server, document source & permissions" text="Production will connect this backend read-only to the Eaststone approved-document file share and use enterprise authentication, database and email services."/><section className="card"><h2>Approved SOP source</h2><code>N:\Controlled Documents\Approved Documents\Approved SOPs</code><p>For a Windows service deployment, configure the UNC path behind the mapped N: drive as <b>EQMS_APPROVED_DOCS_ROOT</b>.</p></section></>}

export default function App(){const[user,setUser]=useState<User|null|undefined>(undefined);useEffect(()=>{if(!getToken()){setUser(null);return}api.me().then(setUser).catch(()=>{api.logout();setUser(null)})},[]);if(user===undefined)return <Loading/>;return <Routes><Route path="/login" element={user?<Navigate to="/"/>:<Login onLogin={setUser}/>}/><Route path="/*" element={user?<Shell user={user} setUser={setUser}><Routes><Route path="/" element={<Dashboard/>}/><Route path="/training" element={<Training/>}/><Route path="/documents" element={<Documents user={user}/>}/><Route path="/complaints" element={<QmsList kind="complaint"/>}/><Route path="/deviations" element={<QmsList kind="deviation"/>}/><Route path="/capa" element={<QmsList kind="capa"/>}/><Route path="/oos" element={<QmsList kind="oos"/>}/><Route path="/risk" element={<QmsList kind="risk"/>}/><Route path="/team" element={<People/>}/><Route path="/audit" element={<Audit/>}/><Route path="/system" element={<System/>}/></Routes></Shell>:<Navigate to="/login"/>}/></Routes>}
